<?php


/**
 * Skeleton subclass for performing query and update operations on the 'factura' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jan 23 14:32:31 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FacturaPeer extends BaseFacturaPeer {

static public function getFactura(array $request) {
        return FacturaPeer::retrieveByPK($request['id']);
    }
} // FacturaPeer
