generator:
  class: sfPropelGenerator
  param:
    model_class:           DetallesCotizacion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              DetallesCotizacion
    plural:                DetallesCotizacions
    route_prefix:          detalles_cotizacion
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        descripcion: { label: Descripción de servicio }
      list:
        display: [cotizacion, cantidad_servicio,  clave, descripcion, precio_servicio]
        title: Descripcion de servicio por cotizacion
        max_per_page: 25
      filter: ~
      form:    ~
      edit:
        title: Editar descripcion de cotizacion numero %cotizacion%
      new:
        title: Nuevo servicio para cotizar
